name: 模块发布

on:
  push:
    paths:
      - 'gradle.properties'
    branches:
      - master

jobs:
  generate-props:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Send
        uses: zcong1993/actions-ding@master
        with:
          dingToken: 814b2467f4a2cd354fe6317e8bf6d2bd544f1c60bb4f1a6971d09f573306a7c6
          body: |
            {
              "msgtype": "markdown",
              "markdown": {
                "title": "开始打包",
                "text": "ClannadUnit 开始打包 V${{ steps.SET-PUBLISH-VERSION.outputs.publish_version }}"
              }
            }